I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 383, in script
    if Mimic == 1:
  File "game/script.rpy", line 383, in <module>
    if Mimic == 1:
NameError: name 'Mimic' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 383, in script
    if Mimic == 1:
  File "C:\Users\metak\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\metak\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\metak\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 383, in <module>
    if Mimic == 1:
NameError: name 'Mimic' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
CaveGame 1.0
Thu Nov 30 15:09:35 2023
