I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 501, in script
    Rey "Look, I’m all good."
Exception: Sayer 'Rey' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 501, in script
    Rey "Look, I’m all good."
  File "/Users/ethanearle/Downloads/Renpy/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/ethanearle/Downloads/Renpy/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Rey' is not defined.

macOS-13.4.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
CaveGame 1.0
Thu Nov 30 14:30:11 2023
